# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 106c2ce8210d494ea3fbca21a41682047f0d38366546e891cf384e0156384d933154ac7c37f6740dd67e3810ac73805dda51516a578b05d121a3357ec1d46b0f

test:
  secret_key_base: 3cfa62ca8828a30dab6e9e0a3074841f6a4800c00978f273130dd448668abb6ceec8e455ace8b78f2a69a268916fef5e87617de2d25c5eaaec8157730eebe76a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
